### ISSUE TITLE
Debug of cfund db

### ISSUE THREAD

**Issue by marcus290** [marcus290/navcoin-core#2]
**debug-cfund-db** is the branch to debug issues with the cfund db of clients running 4.5.1.

This branch is rolled back to commit 913dc25

**Comment by proletesseract** [comment]
### Todo List

- [ ] setup odroid with the debug-cfund branch
- [x] setup 32 bit linux VM with the debug-cfund branch
- [ ] setup 64 bit linux VM with the debug-cfund branch
- [ ] ~~get logs from my stake box which crashed~~
- [ ] investigate block which users reporting as stuck on (2731601)
- [x] collate other debug logs and/or stuck blocks from the community

**Comment by proletesseract** [comment]
### Debug List
- [x] Proposal States after processing each block

**Comment by marcus290** [comment]
I've added debug log output of cfund info 70e9c23 when flag `-debug=cfund` is used.

Not sure if we want all info to be dumped to the log as this would flood the log. Maybe we should only output some proposal/preq fields or only output every 2nd block, etc.
